xgb_params:
  objective: "reg:squarederror"
  tree_method: "hist"
  device: "cuda"
  max_depth: 6
  learning_rate: 0.15
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 1.0
  gamma: 0.1
  lambda: 2.0
  alpha: 1.0
  random_state: 42
  n_estimators: 500
  early_stopping_rounds: 20