insitu_path: "/content/drive/MyDrive/Colab Notebooks/MoData/insitu/insitu_season.parquet.gzip"
basins:
  San_Joaquin:
    shapefile: "/content/drive/MyDrive/Colab Notebooks/MoData/shapes/USCASJ/basin_shape_geog.shp"
    aso: "/content/drive/MyDrive/Colab Notebooks/MoData/aso/USCASJ/aso_spatial.nc"
  Tuolumne:
    shapefile: "/content/drive/MyDrive/Colab Notebooks/MoData/shapes/USCATM/basin_shape_geog.shp"
    aso: "/content/drive/MyDrive/Colab Notebooks/MoData/aso/USCATM/aso_spatial.nc"
daymet_path: "/content/drive/MyDrive/Colab Notebooks/MoData/snowmodel/daymet/filtered_data"
sensors:
  - AGP
  - BCB
  - BGP
  - BSH
  - CHM
  - DAN
  - DPO
  - FLV
  - GEM
  - GRM
  - GRV
  - HNT
  - KSP
  - KUB
  - KUP
  - LLE
  - MHP
  - PSR
  - RCK
  - SLK
  - STL
  - STR
  - SWM
  - TMR
  - TNY
  - TUM
  - UBC
  - VLC
  - WWC
  - DDM
  - GIN
  - GNL
  - HRS
  - KIB
  - LMS
  - PDS
  - REL
  - SLI
  - SMW
  - SPA
  - VLR
  - WHW
coord_crs: "EPSG:4326"
working_crs: "EPSG:32611"
buffer_meters: 5000
